// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticlesBox: typeof import('./components/ArticlesBox.vue')['default']
    ArticlesBoxArticle: typeof import('./components/ArticlesBoxArticle.vue')['default']
    TagsBox: typeof import('./components/TagsBox.vue')['default']
    TagsBoxTag: typeof import('./components/TagsBoxTag.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheNavDarkMode: typeof import('./components/TheNavDarkMode.vue')['default']
    TheNavLangToggle: typeof import('./components/TheNavLangToggle.vue')['default']
    TheNavLinks: typeof import('./components/TheNavLinks.vue')['default']
  }
}

export { }
