// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticlesFeaturedFour: typeof import('./components/Articles/ArticlesFeaturedFour.vue')['default']
    ArticlesFeaturedFourArticle: typeof import('./components/Articles/ArticlesFeaturedFourArticle.vue')['default']
    ArticlesLatest: typeof import('./components/Articles/ArticlesLatest.vue')['default']
    ArticlesLatestArticle: typeof import('./components/Articles/ArticlesLatestArticle.vue')['default']
    ArticlesOpinion: typeof import('./components/Articles/ArticlesOpinion.vue')['default']
    ArticlesOpinionArticle: typeof import('./components/Articles/ArticlesOpinionArticle.vue')['default']
    TagsBox: typeof import('./components/Tags/TagsBox.vue')['default']
    TagsBoxTag: typeof import('./components/Tags/TagsBoxTag.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeadlinesMarquee: typeof import('./components/Articles/TheHeadlinesMarquee.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheNavDarkMode: typeof import('./components/TheNavDarkMode.vue')['default']
    TheNavLangToggle: typeof import('./components/TheNavLangToggle.vue')['default']
    TheNavLinks: typeof import('./components/TheNavLinks.vue')['default']
  }
}

export { }
